const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.TiledBg,
		C3.Behaviors.Flash,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.wrap,
		C3.Behaviors.jumpthru,
		C3.Behaviors.destroy,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Behaviors.EightDir,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{GamePush: 0},
	{Мигание: 0},
	{ТайловыйФон: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Замкнутость: 0},
	{Игрок: 0},
	{СквознаяПлатформа: 0},
	{УничтожатьЗаПределамиМакета: 0},
	{Платформа: 0},
	{Твердый: 0},
	{Пол: 0},
	{телепорт: 0},
	{Якорь: 0},
	{"8Направлений": 0},
	{Вправо: 0},
	{Влево: 0},
	{клик: 0},
	{пол1: 0},
	{уровень3: 0},
	{пол2: 0},
	{next: 0},
	{прыжок: 0},
	{туалет: 0},
	{Пуля: 0},
	{дед: 0}
];

self.InstanceType = {
	GamePush: class extends self.IInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Игрок: class extends self.ISpriteInstance {},
	Платформа: class extends self.ISpriteInstance {},
	Пол: class extends self.ISpriteInstance {},
	телепорт: class extends self.ISpriteInstance {},
	Вправо: class extends self.ISpriteInstance {},
	Влево: class extends self.ISpriteInstance {},
	клик: class extends self.IInstance {},
	пол1: class extends self.ISpriteInstance {},
	уровень3: class extends self.ISpriteInstance {},
	пол2: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	прыжок: class extends self.IInstance {},
	туалет: class extends self.ISpriteInstance {},
	дед: class extends self.ISpriteInstance {}
}